modLoader="javafml"
loaderVersion="[28,)"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="http://my.issue.tracker/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="tardisdecorations"
version="${file.jarVersion}"
displayName="Tardis Decorations"
# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="http://example.com/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
credits="Special Thanks To:" #optional
# A text field displayed in the mod UI
authors="Created by: TheArkNoah05" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Tardis Decorations

This mod aims to add more decorational options for people who like to spice their Tardis interiors up a bit.
This mod was initially created to help PHOEN1X with the designing limitations of his interiors.
Enjoy!
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.tardisdecorations]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[28,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.tardisdecorations]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.tardisdecorations]]
    modId="tardis"
    mandatory=false
    versionRange="[1.4,)"
    ordering="BEFORE"
    side="BOTH"
